import type { EndpointDefinition, JsonSchema } from "./types.js";

export function generateEndpointTypes(endpoints: EndpointDefinition[], options: { namespace?: string } = {}): string {
  const namespace = options.namespace ?? "PremanEndpoints";
  const lines: string[] = [
    "/* eslint-disable */",
    "// Generated by preman-sdk. Do not edit by hand.",
    `export namespace ${namespace} {`,
  ];

  for (const endpoint of endpoints) {
    const name = typeName(endpoint);
    lines.push(`  export type ${name}Request = ${schemaToType(endpoint.requestBodySchema ?? endpoint.request_body_schema)};`);
    lines.push(`  export type ${name}Response = ${schemaToType(endpoint.responseSchema ?? endpoint.response_schema)};`);
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function typeName(endpoint: EndpointDefinition): string {
  const method = title(endpoint.method.toLowerCase());
  const path = endpoint.path ?? endpoint.pathTemplate ?? endpoint.path_template ?? "endpoint";
  const parts = path.split("/").filter(Boolean).map((part) => title(part.replace(/[{}:_-]+/g, " ")));
  return `${method}${parts.join("") || "Root"}`.replace(/[^A-Za-z0-9_]/g, "");
}

function title(value: string): string {
  return value.split(/\s+/).filter(Boolean).map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`).join("");
}

function schemaToType(schema: JsonSchema | undefined): string {
  if (!schema) return "unknown";

  const type = schema["type"];
  if (Array.isArray(type)) {
    return type.map((item) => schemaToType({ ...schema, type: item })).join(" | ");
  }
  if (type === "string") return "string";
  if (type === "number" || type === "integer") return "number";
  if (type === "boolean") return "boolean";
  if (type === "null") return "null";
  if (type === "array") return `${schemaToType(asSchema(schema["items"]))}[]`;
  if (type === "object" || schema["properties"]) return objectSchemaToType(schema);
  if (schema["enum"] && Array.isArray(schema["enum"])) {
    return schema["enum"].map((value) => JSON.stringify(value)).join(" | ");
  }
  return "unknown";
}

function objectSchemaToType(schema: JsonSchema): string {
  const properties = asObject(schema["properties"]);
  if (!properties) return "Record<string, unknown>";
  const required = new Set(Array.isArray(schema["required"]) ? schema["required"].filter((item): item is string => typeof item === "string") : []);
  const fields = Object.entries(properties).map(([key, value]) => {
    const optional = required.has(key) ? "" : "?";
    return `${JSON.stringify(key)}${optional}: ${schemaToType(asSchema(value))};`;
  });
  return `{\n${fields.map((field) => `    ${field}`).join("\n")}\n  }`;
}

function asSchema(value: unknown): JsonSchema | undefined {
  return value && typeof value === "object" && !Array.isArray(value) ? value as JsonSchema : undefined;
}

function asObject(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : undefined;
}
